### ISSUE TITLE
Add CONTRIBUTING.md file to the repository

### ISSUE THREAD

**Issue by Brijeshthummar02** [SartHak-0-Sach/Eureka-AI_travel_planner_full_stack_app#1]
Issue Description: Would it be possible to add a CONTRIBUTING.md file to the repository? Having this file in place would provide clear guidelines for new contributors on how to contribute effectively to the project, including steps for setting up the development environment, coding standards, and the process for submitting pull requests. This will help streamline the contribution process and encourage more participation.

Also assign me to the task i've my pr ready.

**Comment by SartHak-0-Sach** [comment]
Sure, would love to do that. Since you have your PR ready, who am I to go out of the way and do it myself, so consider it assigned😇👍🏻
